#!/usr/bin/env sh

ockam reset
ockam enroll

OCKAM_BROKER_TICKET=$(ockam project ticket)

ockam identity create 
ockam project enroll $OCKAM_BROKER_TICKET 
ockam node create --tcp-listener-address 0.0.0.0:6000
ockam kafka-outlet create \
  --bootstrap-server $REDPANDA_BROKERS