#!/usr/bin/env sh

PRODUCER_TICKET=$(ockam project ticket --attribute role=member)
NAME="producer"

ockam identity create "$NAME"_identity
ockam project enroll $PRODUCER_TICKET --identity "$NAME"_identity
ockam node create "$NAME"_node --identity "$NAME"_identity
ockam kafka-producer create \
  --at "$NAME"_node \
  --project-route /ip4/127.0.0.1/tcp/6000/secure/api

export JAVA_HOME=/opt/homebrew/opt/openjdk
echo "Starting console producer..."
kafka-console-producer --topic demo \
  --bootstrap-server 127.0.0.1:5000 \
  --producer.config plain.config