#!/usr/bin/env sh

CONSUMER_TICKET=$(ockam project ticket --attribute role=member)

NAME="consumer"
ockam identity create "$NAME"_identity
ockam project enroll $CONSUMER_TICKET --identity "$NAME"_identity
ockam node create "$NAME"_node --identity "$NAME"_identity
ockam kafka-consumer create \
  --at "$NAME"_node \
  --project-route /ip4/127.0.0.1/tcp/6000/secure/api

export JAVA_HOME=/opt/homebrew/opt/openjdk
echo "Starting console consumer..."
kafka-console-consumer --topic demo \
  --bootstrap-server 127.0.0.1:4000 \
  --consumer.config plain.config