#!/usr/bin/env sh
NAME="kafkabroker"

ockam reset
ockam enroll

OCKAM_BROKER_TOKEN=$(ockam project ticket --attribute component=kafkabroker)

ockam identity create "$NAME"_identity
ockam project enroll $OCKAM_BROKER_TOKEN --identity "$NAME"_identity
ockam node create $NAME --identity "$NAME"_identity
ockam kafka-outlet create --bootstrap-server $REDPANDA_BROKERS --at $NAME
ockam relay create broker --at /project/default --to "/node/$NAME"

